config/routes.rb
Bumpyride::Application.routes.draw do
  resources :favorites

  get "home/index"

  resources :users

  resources :photos do
    resources :comments
  end

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  attr_accessible :body, :user_id
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  # attr_accessible :title, :body
end

app/models/photo.rb
#require 'RMagick'

class Photo < ActiveRecord::Base
  belongs_to :user
  attr_accessible :image, :title, :image, :user_id

  mount_uploader :image, ImageUploader

  has_many :comments, :dependent => :destroy

  validates :image,  :presence => true
  validates :user_id, :presence => true

  #def as_json(options={})
  #  {:title       => self.title,
  #   :image       => self.image,
  #   :user_id     => self.user_id,
  #   :comments    => self.comments
  #  }
  #end

  def as_json(options={})
    super(
        :include => [:comments]
    )
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :photo
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :full_name, :username
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.create(params[:comment])
    redirect_to photo_path(@photo)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.json
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: 'Favorite was successfully created.' }
        format.json { render json: @favorite, status: :created, location: @favorite }
      else
        format.html { render action: "new" }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.json
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to favorites_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@photos = Photo.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_form.html.haml
= form_for @favorite do |f|
  - if @favorite.errors.any?
    #error_explanation
      %h2= "#{pluralize(@favorite.errors.count, "error")} prohibited this favorite from being saved:"
      %ul
        - @favorite.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :photo
    = f.text_field :photo
  .actions
    = f.submit 'Save'

app/views/favorites/edit.html.haml
%h1 Editing favorite

= render 'form'

= link_to 'Show', @favorite
\|
= link_to 'Back', favorites_path

app/views/favorites/index.html.haml
%h1 Listing favorites

%table
  %tr
    %th User
    %th Photo
    %th
    %th
    %th

  - @favorites.each do |favorite|
    %tr
      %td= favorite.user
      %td= favorite.photo
      %td= link_to 'Show', favorite
      %td= link_to 'Edit', edit_favorite_path(favorite)
      %td= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Favorite', new_favorite_path

app/views/favorites/new.html.haml
%h1 New favorite

= render 'form'

= link_to 'Back', favorites_path

app/views/favorites/show.html.haml
%p#notice= notice

%p
  %b User:
  = @favorite.user
%p
  %b Photo:
  = @favorite.photo

= link_to 'Edit', edit_favorite_path(@favorite)
\|
= link_to 'Back', favorites_path

app/views/home/index.html.haml
-#.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{:type => "button", 'data-toggle' => "collapse", 'data-target' => ".nav-collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      -#%h1 
      = link_to 'BumpyRide', "", class: "brand"

      .nav-collapse.collapse
        %ul.nav
          %li
            =link_to 'Upload', '#'  

#photos
  .row

:javascript
  $(function() {
    // Bumpyride is the app name
    window.router = new Bumpyride.Routers.PhotosRouter({photos: #{@photos.to_json.html_safe}});
    //window.router2 = new Bumpyride.Routers.CommentsRouter({comments: #{@comments.to_json.html_safe}});
    Backbone.history.start();
  });
  $(document).ready(function() {
    $('ul.thumbnails img').each(function() {
      if(screen.pixelDepth != undefined && screen.pixelDepth == 32) {
        this.src = $(this).data('retina');
      } else {  
        this.src = $(this).data('src');
      }
    });
  });

:javascript
  $(document).on( "click", "a.route", function( e ) {
    e.preventDefault();
    router.navigate( $(this).attr("href"), { trigger: true } );
  });

%noscript
  #NoScript
    %h1 You need to enable Javascript.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bumpyride</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <meta charset='utf-8' content='width=device-width, initial-scale=1.0' name='viewport'>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <%= javascript_include_tag "application" %>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap.js"></script>
  <%= csrf_meta_tags %>

</head>
<body>
<div class='navbar navbar-fixed-top'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='btn btn-navbar' data-target='.nav-collapse' data-toggle='collapse' type='button'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </a>
      <a href="/" class="brand">BumpyRide</a>
      <div class='nav-collapse collapse'>
        <ul class='nav'>
          <li>
            <a href="/photos/new">Upload</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">

<%= yield %>

</div>

</body>
</html>

app/views/photos/_form.html.haml
= form_for @photo, :html => { :multipart => true } do |f|
  - if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .field.file-wrapper
    = f.file_field :image, class: "file-upload-large"
    %a.button{ :class => 'btn btn-success btn-large'} Select bicycle photo
    %span.fileName &nbsp;
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.hidden_field :user_id, value: "1"
  .actions
    = f.submit 'Upload', class: "btn btn-default"


:javascript
  $('input[type=file]').bind('change', function() {
    if ($(this).val()) { $('span.fileName').html( $(this).val().replace(/^.*\\/, '') ) }
  });

app/views/photos/edit.html.haml
%h1 Edit photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/index.html.haml
%h1 Photos

%table
  %tr
    %th Image
    %th Title
    -#%th User
    %th
    %th
    %th

  - @photos.each do |photo|
    %tr
      %td= link_to image_tag(photo.image_url(:mini).to_s), photo
      %td= photo.title
      -# %td= photo.user
      %td= link_to 'Show', photo
      %td= link_to 'Edit', edit_photo_path(photo)
      %td= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Photo', new_photo_path

app/views/photos/new.html.haml
%h1 New bumpy ride

= render 'form'

= link_to 'Back', root_path

app/views/photos/show.html.haml
%p#notice= notice
= link_to 'Home', photos_path
\|
= link_to 'Upload', new_photo_path
%h1
  = @photo.title
%p
  = image_tag @photo.image_url(:medium).to_s

-#%p
  %b User:
  = @photo.user

- @photo.comments.each do |comment|
  %p 
    = comment.body

%h3 Add a comment:
= form_for([@photo, @photo.comments.build]) do |f|
  .field
    = f.text_field :body
  -#.field
    = f.hidden_field :user_id, value: "1"
  -#.field
    = f.hidden_field :photo_id, value: "1"
  .actions
    = f.submit 'Save Comment', class: "btn btn-primary"


= link_to 'Edit', edit_photo_path(@photo)
\|
-#= link_to 'Back', photos_path
= link_to 'Home', photos_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :full_name
    = f.text_field :full_name
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Username
    %th Full name
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.username
      %td= user.full_name
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Full name:
  = @user.full_name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path